nodes:
  - name: "node1"
    vcpu: 6
    ram: 8
    disk: 80
    auth_url: "http://192.168.0.51/identity"
  - name: "node2"
    vcpu: 6
    ram: 8
    disk: 80
    auth_url: ""
  - name: "node3"
    vcpu: 6
    ram: 8
    disk: 80
    auth_url: ""
  - name: "node4"
    vcpu: 6
    ram: 8
    disk: 80
    auth_url: ""