nodes:
  - name: "node1"
    vcpu: 6
    ram: 6
    disk: 80
    auth_url: "http://192.168.0.83/identity"
  - name: "node4"
    vcpu: 6
    ram: 6
    disk: 80
    auth_url: "http://192.168.0.85/identity"