username: "admin"
password: "1234"
project_name: "admin"
domain_name: "default"
external_network: "public"
external_network_subnet: "public-subnet"
default_router_name: "router"
default_internal_network: "default"
default_flavors:
  - "kws_small"
  - "kws_medium"
  - "kws_large"