username: "admin"
password: #시스템 비밀번호 입력
project_name: "admin"
domain_name: "default"
external_network:
  name: "public"
  subnet: "public-subnet"
  cidr: "192.168.0.0/24"
internal_network:
  name: "default"
  subnet: "default-subnet"
  cidr: "192.168.233.0/24"
router: "router"
flavors:
  - name: "kws_small"
    vcpu: 1
    ram: 512
    disk: 5
  - name: "kws_medium"
    vcpu: 1
    ram: 1024
    disk: 10
  - name: "kws_large"
    vcpu: 2
    ram: 2048
    disk: 20