auth_url: "http://192.168.0.51/identity"
username: "admin"
password: "1234"
project_name: "admin"
domain_name: "default"
external_network: "public"
external_network_subnet: "public-subnet"
default_internal_network: "shared"
default_flavors:
  - "kws_small"
  - "kws_medium"
  - "kws_large"